### ISSUE TITLE
Missing script reference on Stable-0.5.0a (27 Apr 2020)

### ISSUE THREAD

**Issue by kenshin12269** [DreamersIncStudios/ECS-IAUS-sytstem#18]
I really love to see your work going!

In fact, there is some missing script show when opened project first time. I believe it's some componentProxy scripts.

![image](https://user-images.githubusercontent.com/49503816/82740974-99393e00-9d88-11ea-9626-1a06da80c469.png)

**Comment by DreamersIncStudios** [comment]
Let me download the stable project and take a look at work is going on.

**Comment by DreamersIncStudios** [comment]
Scenes ECS IAUS and Programmers Playground are not longer proper scene to be used in this project as those scripts have been remove. Most likely, they are leftover parts of when I first implement Infinite Axis Utility using Mono behaviors. I will mark them for deletion and fix in the next push. 
For a sample Scene, please use Influence Map work area. I am working on my name schemes.
Sorry.

**Comment by DreamersIncStudios** [comment]
Also, consider disabling 325 of the Enemy gameObject. This was torture early torture test.

**Comment by kenshin12269** [comment]
Thanks for the fast reply! I'll try scene InfluenceMap!
