### ISSUE TITLE
Running Spawn Scene

### ISSUE THREAD

**Issue by mlflabs** [DreamersIncStudios/ECS-IAUS-sytstem#24]
Hello,

thanks for sharing your work on ecs ai.  its very informative.

I just need a bit of help, when running the spawn scene, im getting errors. I have uploaded a screenshot.

Also, could you maybe write quick, couple sentence instructions on how to start using your system?  I know its work in progress, a lot will change, but just maybe a short paragraph, this will provide a good entry point into using it, or a 2min youtube video of you just showing a quick setup of an npc, whats needed to get started.

thanks for your hard work.
![Screen Shot 2020-08-04 at 1 47 10 PM](https://user-images.githubusercontent.com/20916673/89257943-bed0a680-d659-11ea-98ad-a3dd1c141110.png)

Mike

**Comment by DreamersIncStudios** [comment]
The scene which you are using need some major update. I have been avoiding it as I have not how to approach Enemy detection and Updating the influence grid without major performance issues. Currently the best scene to use is the "new spawn test scene." This project really isn't ready to be used in a project. It more of a sample project for those trying to learn Unity DOTS with a real practical application.  To understand what is going attempted here, I would recommend starting with [Dave Mark's GDC talk on Guild Wars 2 AI system](https://www.gdcvault.com/play/1021848/Building-a-Better-Centaur-AI) which is the basis for this project. 

So how does it all work? 
First you will need to create IAUS ScriptableObject agent assets. This is locate under Assets>Create> RPG> Enemy-IAUS and Squad-IAUS. Hope to later replace this with a CSV importer and editor window.  Select the state you want to include and change score valuesif wanted. Note not all states are implemented. Please watch linked video to understand state scoring. 
![image](https://user-images.githubusercontent.com/54472412/89292144-dc861780-d629-11ea-9431-d327b2db3efb.png)
You will then need to make a Squad IAUS asset.
