### ISSUE TITLE
Clarification on scripts folder

### ISSUE THREAD

**Issue by slonoed** [DreamersIncStudios/ECS-IAUS-sytstem#30]
_Sorry for using issues for questions._

This repo is an excellent source of learning. Many kudos!
I have a question which I can't find an answer. Consider this is a request to update readme (answer to issue would work perfectly as well).

Repo itself has somehow custom folders structure. What is the difference between `/Assets/Systems` and `/Assets/Scripts/IAUS/Scripts/`?

**Comment by DreamersIncStudios** [comment]
The `/Assets/Scripts/Systems/` refers to other project created outside of this one or used in multiple projects.  I tried to structure the folders so the all code for a given system is contain in its given folder. That why when I update a given system I just replace the whole folder. Honestly, `Assets/Scripts` folder is poorly name and will be updated in a future reactor. This should be coming once Branch Alpha-0.7.1 is becomes the stable branch.

**Comment by slonoed** [comment]
Thanks for the explanation!
